### ISSUE TITLE
does random directory require translation?

### ISSUE THREAD

**Issue by Blueberryy** [dekdevy/hordes-loc#1344]
i'm planning to update Russian translation and i saw that there's ``random`` directory on this repository that has some names.
It needs new files to be created? like ``name_russian.js`` or i just need to add new ``const`` like ``adjectives russian =``?

**Comment by dekdevy** [comment]
Hey. random names do not need a translation, they are for randomly generated names and bot names. We've got plenty there now :) Thanks for offering your time though!
