### ISSUE TITLE
Won't work on Safari

### ISSUE THREAD

**Issue by Dolfost** [dekdevy/hordes-loc#1346]
I opened the game, completed the tutorial, and the game froze - the interface is clickable but the game is frozen.

WebGL2 is enabled:
![image](https://github.com/dekdevy/hordes-loc/assets/59747489/aff91a0f-cf3c-4703-9a42-6366e272050c)
![image](https://github.com/dekdevy/hordes-loc/assets/59747489/697dfe78-4e0b-43e4-b2ee-d1b664b4a687)

Interface is clickable, game is frozen.
![image](https://github.com/dekdevy/hordes-loc/assets/59747489/c204b4fc-f9b1-42c9-b3ae-a3b94ccb71e9)

PC: Mac book air M2 Ventura 13.4.1
Safari: v16.5.1

**Comment by dekdevy** [comment]
hey. please report on discord, this is a localization repository. sorry. make sure to include console content.

**Comment by Dolfost** [comment]
@dekdevy Im sorry, I just have searched the hordes.io GitHub repo, made the issue and then realised that this is just localisations repo. Sorry again.
