### ISSUE TITLE
Formal vs Informal addressing of the Player

### ISSUE THREAD

**Issue by Campinator** [dekdevy/hordes-loc#758]
In many languages (Spanish, French, Portuguese, for example), there is a difference in the formal "you" and informal "you". Especially for languages where the translations were all initially done by an automatic translator, there is some disparity between usage, though it seems like right now more translations use the formal than informal. Should the player be referred to formally or informally by the game?

**Comment by dekdevy** [comment]
In german as well, it should always be informal; at least thats what i gather from other german translations.

**Comment by Campinator** [comment]
Ah ok, it seems like almost every language other than English has separate "you" cases. Do you think all translations should use the informal when talking to the player, or was that just a remark on how it currently is?

**Comment by drifted-mdl** [comment]
In some sentences, the formal sounds better and more appropriate. It's not really possible to distinguish if you don't know the language.

**Comment by dekdevy** [comment]
I can only tell you what i gather from german translations, for example WoW or Overwatch, League of Legends, they are fully informal, so i would suggest doing the same. (when the player is adressed). Of course if you have a dialogue between NPCs then you'd use whatever is appropriate for the conversation.
