### ISSUE TITLE
Culling of generator files

### ISSUE THREAD

**Issue by dekdevy** [dekdevy/hordes-loc#797]
link.js and name.js

name.js contains 500 syllables, allowing for well over 60 billion name combinations.
link.js contains 1220 words for roughly 54 million link combinations.

Together they make up a serious amount of data, something in the ballpark of 20-40kb.
We don't need either of these quantities and filesizes. The files are critical to the page load as nothing can be displayed before the files have been loaded. Plus, many of the entries are low quality. 

Often times you can improve the quality of something by creating alot of it, then weeding out the trash.

I need someone to reduce the name.js syllables from 500 to 300, and the link.js words from 1220 to 500 by removing low quality words/syllables. things to consider:
- how well does it fit into a fantasy / game setting
- is it at all interesting
- does it allow for funny or attention grabbing combinations
- could they be too obscure for the target audience to understand

Examples to remove from a quick glance:
disclosure, refurbishment, motherland, knee, paraphernalia, century, millenium, big, bad, red, blue, cyan, expanding, corrosive, pernicious.
Not saying those are bad, they just aren't good enough to be considered the best, which is all we want for these lists.

**Comment by drifted-mdl** [comment]
All done.

**Comment by dekdevy** [comment]
looking good, thanks!
