### ISSUE TITLE
Add arabic support

### ISSUE THREAD

**Issue by yazeed** [dekdevy/hordes-loc#921]
If you add Arabic support, the community could start translating that as well.

**Comment by Malfrador** [comment]
You should be able to just add arabic translations. For example, if you have this:
`  description: {
    en: 'Archers deal high single target damage and bursty...',
    ru: 'Лучники наносят высокий урон по одиночной цели и...'
  }`
you can just add arabic below the russian text:
`  description: {
    en: 'Archers deal high single target damage and bursty...',
    ru: 'Лучники наносят высокий урон по одиночной цели и...',
    ar: 'Your arabic text'
  }`

"ar" is the IANA language code for arabic.

**Comment by drifted-mdl** [comment]
If we don't have a particular language in the repository, we are not excluding it, we just don't have anyone who can provide accurate bulk translations.

**Comment by Malfrador** [comment]
The only issue might be right-to-left writing. Not sure if the current translation system handles this well.

> If we don't have a particular language in the repository, we are not excluding it, we just don't have anyone who can provide accurate bulk translations.

**Comment by twt-tsunami1** [comment]
Oh god.
